### ISSUE TITLE
Quix Docs link changed

### ISSUE THREAD

**Issue by EvgenyAlterman** [prestodb/prestodb.github.io#210]
The new link is https://wix-incubator.github.io/quix/

In this file:
https://github.com/prestodb/prestodb.github.io/blob/bdf686d5af9fa5fa36c1417cac174ebcbb36e1ed/website/static/data/Projects_Clients.js#L29

**Comment by EvgenyAlterman** [comment]
@wanglinsong  But The link didn't changed as i See...
https://github.com/prestodb/prestodb.github.io/blob/bdf686d5af9fa5fa36c1417cac174ebcbb36e1ed/website/static/data/Projects_Clients.js#L37

**Comment by wanglinsong** [comment]
> @wanglinsong But The link didn't changed as i See...
> 
> https://github.com/prestodb/prestodb.github.io/blob/bdf686d5af9fa5fa36c1417cac174ebcbb36e1ed/website/static/data/Projects_Clients.js#L37
> 
> 
> As I can't open PR, I can't really contribute. need someone to do it

https://github.com/prestodb/prestodb.github.io/pull/218
