### ISSUE TITLE
Website should have an url redirect at /slack that redirects to latest Slack signup

### ISSUE THREAD

**Issue by psbell-meta** [prestodb/prestodb.github.io#211]
For ease of invitation and consistency across future changes, we should have prestodb.io/slack redirect to slack signup, new links, articles, conference talks etc. can always reference this url which is easy to remember and share, and we can always ensure the redirect is to the correct page

http://prestodb.io/slack should redirect to https://communityinviter.com/apps/prestodb/prestodb

**Comment by mcknightd** [comment]
Yes, we can do this directly in the github editor pretty quickly. When you get time I'll walk you through it.

**Comment by psbell-meta** [comment]
@mcknightd can we implement this immediately?  Was hoping to show the URL during a presentation today, the goal here is that all presentations and references can always refer to that URL and we use redirect to ensure it's correct in the future no matter how we do sign up

**Comment by mcknightd** [comment]
I can create a PR here shortly

**Comment by mcknightd** [comment]
@psbell-meta https://github.com/prestodb/prestodb.github.io/pull/212

**Comment by wanglinsong** [comment]
> @mcknightd can we implement this immediately? Was hoping to show the URL during a presentation today, the goal here is that all presentations and references can always refer to that URL and we use redirect to ensure it's correct in the future no matter how we do sign up

Update is merged.

**Comment by rohanpednekar** [comment]
Thanks @mcknightd 

https://prestodb.io/slack redirects to https://communityinviter.com/apps/prestodb/prestodb now.
