### ISSUE TITLE
Connecting Presto Delta Lake Connector to External Metastore and Delta Tables on Azure ADLS Gen2

### ISSUE THREAD

**Issue by prem-jindalx** [prestodb/prestodb.github.io#221]
Presto - Connector not connecting with  External Metastore (MSSQL) and Delta Tables on Azure ADLS Gen2. What are the attributes to be specified for MSSQL HiveMetastore and ADLS Gen2

**Comment by ArpanRoy-Ahana** [comment]
These might help you get started @prem-jindalx.

https://stackoverflow.com/questions/70330250/how-to-connect-to-azure-data-lake-storage-using-presto-on-python

https://arsenvlad.medium.com/presto-querying-data-in-azure-blob-storage-and-azure-data-lake-store-99149c8c796

Meanwhile, please feel free to ask any issues  you have (including this one) in the official PrestoDB slack channel: 
https://join.slack.com/t/prestodb/shared_invite/zt-1y9x0svg1-j27kPlZS~Elg1EOlt1nShQ

Thanks,
Arpan

**Comment by alileclerc** [comment]
hi @prem-jindalx, I'm going to close this issue now. Feel free to join us at the slack channel if you have more questions.
