### ISSUE TITLE
Menu item "Presto C++" rendering is not correct

### ISSUE THREAD

**Issue by dnskr** [prestodb/prestodb.github.io#273]
Menu item `Presto C++` shows `Overview`, `Motivation and Vision` and `Supported Use Cases` as pages.
The issue disappeared in `0.288` docs, but came back after https://github.com/prestodb/prestodb.github.io/pull/269 or https://github.com/prestodb/prestodb.github.io/pull/272.

Current view:
<img width="324" alt="Screenshot 2024-07-22 at 15 04 34" src="https://github.com/user-attachments/assets/7d2ff672-afd8-49bc-b754-41be84e1eb9b">

Expected view (from Presto source code):
<img width="296" alt="Screenshot 2024-07-22 at 15 06 38" src="https://github.com/user-attachments/assets/98506907-4c32-4ed6-991c-90a329b85028">

**Comment by dnskr** [comment]
FYI @ZacBlanco and @yhwang

**Comment by yhwang** [comment]
This PR: #277 should fix the issue
